### ISSUE TITLE
six.moves.queue import Queue

### ISSUE THREAD

**Issue by rrohana** [facebook/augmented-traffic-control#151]
Hi
I followed your guide on installing -- When I run the service I get
 File "/bin/atcd", line 12, in <module>
    from atcd.scripts import runner
  File "/usr/lib/python2.7/site-packages/atcd/scripts/runner.py", line 19, in <module>
    from atcd.AtcdDeviceTimeoutTask import AtcdDeviceTimeoutTask
  File "/usr/lib/python2.7/site-packages/atcd/AtcdDeviceTimeoutTask.py", line 10, in <module>
    from atcd.AtcdThriftHandlerTask import AtcdThriftHandlerTask
  File "/usr/lib/python2.7/site-packages/atcd/AtcdThriftHandlerTask.py", line 41, in <module>
    from atcd.AtcdDBQueueTask import AtcdDBQueueTask
  File "/usr/lib/python2.7/site-packages/atcd/AtcdDBQueueTask.py", line 13, in <module>
    from sparts.tasks.queue import QueueTask
  File "/usr/lib/python2.7/site-packages/sparts/tasks/queue.py", line 10, in <module>
    from sparts.collections import PriorityQueue, UniqueQueue
  File "/usr/lib/python2.7/site-packages/sparts/collections.py", line 3, in <module>
    from six.moves.queue import Queue
ImportError: No module named queue

OS = Centos7

**Comment by chantra** [comment]
Hi @rrohana 

This seems related to #74 . Can you check the version of six.

**Comment by chantra** [comment]
Hi @rrohana 

I did  not get any update from your side. I believe #74 answers your question. I will close this issue for now, feel free to get back to us if you have any other issues.

**Comment by rrohana** [comment]
HI
Sorry - was on vacation
/usr/bin/env python -c 'import six; print six.__version__' 
1.3.0

**Comment by rrohana** [comment]
HI again   -- I fixed it by upgrading to six-1.9
However, I have a different problem now :
INFO:AtcdVService.AtcdNBServerTask:AtcdNBServerTask Server Started on 127.0.0.1:9090
CRITICAL:AtcdVService.AtcdLinuxShaper:One of the following interfaces does not exist: eth1, eth0
ERROR:sparts.tasks:Error creating task, AtcdLinuxShaper
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sparts/vtask.py", line 313, in init
    t.initTask()
  File "/usr/lib/python2.7/site-packages/atcd/backends/linux.py", line 48, in initTask
    super(AtcdLinuxShaper, self).initTask()
  File "/usr/lib/python2.7/site-packages/atcd/AtcdThriftHandlerTask.py", line 227, in initTask
    self._links_lookup()
  File "/usr/lib/python2.7/site-packages/atcd/backends/linux.py", line 65, in _links_lookup
    raise Exception(msg)
Exception: One of the following interfaces does not exist: eth1, eth0
ERROR:AtcdVService:Unexpected Exception during init
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sparts/vservice.py", line 268, in _runloop
    instance._createTasks()
  File "/usr/lib/python2.7/site-packages/sparts/vservice.py", line 167, in _createTasks
    self.tasks.init()
  File "/usr/lib/python2.7/site-packages/sparts/vtask.py", line 332, in init
    len(exceptions))
Exception: Unable to start service (1 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDeviceTimeoutTask.AtcdDeviceTimeoutTask object at 0x2453290> to stop...
DEBUG:AtcdVService:Waiting for <atcd.backends.linux.AtcdLinuxShaper object at 0x24535d0> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDBQueueTask.AtcdDBQueueTask object at 0x2453690> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdThriftHandlerTask.AtcdNBServerTask object at 0x244d590> to stop...
INFO:AtcdVService:Instance shut down gracefully

**Comment by rrohana** [comment]
ignore
