### ISSUE TITLE
Starting atcd failed

### ISSUE THREAD

**Issue by tehbrut** [facebook/augmented-traffic-control#249]
Hi. I configure atcd with https://facebook.github.io/augmented-traffic-control/docs/install.html
But when i execute atcd --atcd-lan ens192 --atcd-wan ens160 (as a root)
I get error:

INFO:AtcdVService.AtcdNBServerTask:AtcdNBServerTask Server Started on 127.0.0.1:9090
INFO:AtcdVService.AtcdLinuxShaper:Calling initialize_shaping_system
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -F FORWARD
ERROR:sparts.tasks:Error creating task, AtcdLinuxShaper
Traceback (most recent call last):
  File "/root/dev/atc/venv/lib/python2.7/site-packages/sparts/vtask.py", line 313, in init
    t.initTask()
  File "/root/dev/atc/venv/lib/python2.7/site-packages/atcd/backends/linux.py", line 48, in initTask
    super(AtcdLinuxShaper, self).initTask()
  File "/root/dev/atc/venv/lib/python2.7/site-packages/atcd/AtcdThriftHandlerTask.py", line 233, in initTask
    self.initialize_shaping_system()
  File "/root/dev/atc/venv/lib/python2.7/site-packages/atcd/backends/linux.py", line 73, in initialize_shaping_system
    self._initialize_iptables()
  File "/root/dev/atc/venv/lib/python2.7/site-packages/atcd/backends/linux.py", line 81, in _initialize_iptables
    self.run_cmd(cmd)
  File "/root/dev/atc/venv/lib/python2.7/site-packages/atcd/AtcdThriftHandlerTask.py", line 561, in run_cmd
    return subprocess.call(shlex.split(cmd))
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR:AtcdVService:Unexpected Exception during init
Traceback (most recent call last):
  File "/root/dev/atc/venv/lib/python2.7/site-packages/sparts/vservice.py", line 268, in _runloop
    instance._createTasks()
  File "/root/dev/atc/venv/lib/python2.7/site-packages/sparts/vservice.py", line 167, in _createTasks
    self.tasks.init()
  File "/root/dev/atc/venv/lib/python2.7/site-packages/sparts/vtask.py", line 332, in init
    len(exceptions))
Exception: Unable to start service (1 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDeviceTimeoutTask.AtcdDeviceTimeoutTask object at 0x11e4990> to stop...
DEBUG:AtcdVService:Waiting for <atcd.backends.linux.AtcdLinuxShaper object at 0x11e4d90> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDBQueueTask.AtcdDBQueueTask object at 0x11e6050> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdThriftHandlerTask.AtcdNBServerTask object at 0x11e4f90> to stop...
INFO:AtcdVService:Instance shut down gracefully

**Comment by chantra** [comment]
@tehbrut 
is seems `iptables` is not found on your system, at least not at this location.
```
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -F FORWARD
..
..
OSError: [Errno 2] No such file or directory
```

What Os do you run, where is `iptables` located on your filesystem?

**Comment by tehbrut** [comment]
@chantra 
Yes, i figure it out. It's OpenSuse
I create symbolic link from /usb/sbin/iptables to /sbin/iptables and it's works well now.

**Comment by chantra** [comment]
Iirc there should me a command line arguments you can use to specify iptables location so you don't need to symlink it.

**Comment by chantra** [comment]
yeah `--atcd-iptables`
