### ISSUE TITLE
Hello, do you have a look at this problem

### ISSUE THREAD

**Issue by xuzhitong89** [facebook/augmented-traffic-control#259]
[14/Apr/2016 02:09:15] "GET /api/v1/token/ HTTP/1.1" 500 17103
Internal Server Error: /api/v1/token/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/atc_api/views.py", line 40, in decorator
    return method(cls, request, service, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/atc_api/views.py", line 233, in get
    stuff = service.requestToken(address, duration)
  File "/usr/local/lib/python2.7/dist-packages/atc_thrift/Atcd.py", line 424, in requestToken
    return self.recv_requestToken()
  File "/usr/local/lib/python2.7/dist-packages/atc_thrift/Atcd.py", line 436, in recv_requestToken
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
    sz = self.readI32()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
    buff = self.trans.readAll(4)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 58, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 276, in read
    self.readFrame()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 282, in readFrame
    self.__rbuf = StringIO(self.__trans.readAll(sz))
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 58, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 105, in read
    buff = self.handle.recv(sz)
error: [Errno 104] Connection reset by peer

**Comment by zfjagann** [comment]
This appears to be an issue with atc_api communicating with atcd. Can you look for atcd messages in `/var/log/messages` or `/var/log/syslog` and paste any error messages you see from `atcd` around the time of the failure?

**Comment by chantra** [comment]
@xuzhitong89 can you provide the logs requested by @zfjagann ?

**Comment by chantra** [comment]
@xuzhitong89 
We did not hear back from you, I will close this issue for now. If you still experiment it, please open a new issue and provide the logs requested by @zfjagann
