### ISSUE TITLE
ATC is not running

### ISSUE THREAD

**Issue by winzows** [facebook/augmented-traffic-control#313]
**atc is not running
terminal show:**
```
[17/May/2017 12:28:23] "GET /api/v1/token/ HTTP/1.1" 502 46
atcdClient: TTransportException: Could not connect to any of [('127.0.0.1', 9090)]
[17/May/2017 12:28:25] "GET /api/v1/token/ HTTP/1.1" 502 46
atcdClient: TTransportException: Could not connect to any of [('127.0.0.1', 9090)]
[17/May/2017 12:28:33] "GET /api/v1/token/ HTTP/1.1" 502 46
atcdClient: TTransportException: Could not connect to any of [('127.0.0.1', 9090)]
[17/May/2017 12:28:34] "GET /api/v1/token/ HTTP/1.1" 502 46
atcdClient: TTransportException: Could not connect to any of [('127.0.0.1', 9090)]
[17/May/2017 12:28:34] "GET /api/v1/token/ HTTP/1.1" 502 46
```
**Browser show：**
```
Notifications
Could not fetch current token: [object Object]4
Could not fetch auth info: [object Object]4
Could not fetch current token: [object Object]
```
I need help  thanks！

**Comment by winzows** [comment]
**And this step is wrong**
```
ubuntu@ubuntu-Zhaoyang-E49L:~/atcui/atcui$ sudo atcd
[sudo] ubuntu 的密码： 
Traceback (most recent call last):
  File "/usr/local/bin/atcd", line 12, in <module>
    from atcd.scripts import runner
  File "/usr/local/lib/python3.5/dist-packages/atcd/scripts/runner.py", line 19, in <module>
    from atcd.AtcdDeviceTimeoutTask import AtcdDeviceTimeoutTask
  File "/usr/local/lib/python3.5/dist-packages/atcd/AtcdDeviceTimeoutTask.py", line 10, in <module>
    from atcd.AtcdThriftHandlerTask import AtcdThriftHandlerTask
  File "/usr/local/lib/python3.5/dist-packages/atcd/AtcdThriftHandlerTask.py", line 25, in <module>
    from atc_thrift import Atcd
  File "/usr/local/lib/python3.5/dist-packages/atc_thrift/Atcd.py", line 583
    except TrafficControlException, failure:
                                  ^
SyntaxError: invalid syntax
ubuntu@ubuntu-Zhaoyang-E49L:~/atcui/atcui$
```

Let me thank you in the name of us all!

**Comment by chantra** [comment]
Hi @winzows 

This is because you are running python 3, which is not supported by ATC.

Please use python 2.7 by either creating a virtual environment with `virtualenv` or prepending your commands with `python2.7`.

**Comment by winzows** [comment]
thanks！
