### ISSUE TITLE
Switch network control failed

### ISSUE THREAD

**Issue by lycfr** [facebook/augmented-traffic-control#318]
executable code:sudo --atcd-wan eth0 --atcd-lan wlan0
prompt:
ERROR:sparts.tasks:Error creating task, AtcdNBServerTask
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 313, in init
    t.initTask()
  File "/usr/local/lib/python2.7/dist-packages/sparts/tasks/thrift.py", line 146, in initTask
    self.server.prepare()
  File "/usr/local/lib/python2.7/dist-packages/thrift/server/TNonblockingServer.py", line 256, in prepare
    self.socket.listen()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 185, in listen
    self.handle.bind(res[4])
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
INFO:AtcdVService.AtcdLinuxShaper:Calling initialize_shaping_system
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -F FORWARD
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on wlan0
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on wlan0
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:Restoring shaped connection from DB
ERROR:AtcdVService:Unexpected Exception during init
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 268, in _runloop
    instance._createTasks()
  File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 167, in _createTasks
    self.tasks.init()
  File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 332, in init
    len(exceptions))
Exception: Unable to start service (1 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDeviceTimeoutTask.AtcdDeviceTimeoutTask object at 0x7ff244717bd0> to stop...
DEBUG:AtcdVService:Waiting for <atcd.backends.linux.AtcdLinuxShaper object at 0x7ff2447179d0> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDBQueueTask.AtcdDBQueueTask object at 0x7ff244717950> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdThriftHandlerTask.AtcdNBServerTask object at 0x7ff2447178d0> to stop...
INFO:AtcdVService:Instance shut down gracefully

But I can do it normally:sudo python manage.py runserver 0.0.0.0:8000
Everything else is normal,
What's the reason.

**Comment by chantra** [comment]
> error: [Errno 98] Address already in use



There is already another atcd process running.
