### ISSUE TITLE
sudo: atcd: command not found

### ISSUE THREAD

**Issue by dalmasi** [facebook/augmented-traffic-control#357]
Hi everyone!

I'm trying to run command $sudo atcd in order to start the atcd service. When i run this command i get this error: **sudo: atcd: command not found.**
Then, I try just run **$atcd** and it's run but with a lot of errors:

INFO:AtcdVService.AtcdNBServerTask:AtcdNBServerTask Server Started on 127.0.0.1:9090
ERROR:AtcdVService.AtcdDBQueueTask:Unable to access db file: /var/lib/atcd.db
ERROR:AtcdVService.AtcdDBQueueTask:Unable to initialize DB from file "/var/lib/atcd.db"
Traceback (most recent call last):
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/AtcdDBQueueTask.py", line 32, in initTask
    self.sqlite_manager = SQLiteManager(self.sqlite_file, self.logger)
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/db_manager.py", line 31, in __init__
    with self._get_conn() as conn:
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/db_manager.py", line 71, in _get_conn
    conn = sqlite3.connect(self.file_name)
OperationalError: unable to open database file
ERROR:sparts.tasks:Error creating task, AtcdDBQueueTask
Traceback (most recent call last):
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/sparts/vtask.py", line 313, in init
    t.initTask()
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/AtcdDBQueueTask.py", line 32, in initTask
    self.sqlite_manager = SQLiteManager(self.sqlite_file, self.logger)
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/db_manager.py", line 31, in __init__
    with self._get_conn() as conn:
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/db_manager.py", line 71, in _get_conn
    conn = sqlite3.connect(self.file_name)
OperationalError: unable to open database file
CRITICAL:AtcdVService.AtcdLinuxShaper:One of the following interfaces does not exist: eth1, eth0
ERROR:sparts.tasks:Error creating task, AtcdLinuxShaper
Traceback (most recent call last):
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/sparts/vtask.py", line 313, in init
    t.initTask()
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/backends/linux.py", line 48, in initTask
    super(AtcdLinuxShaper, self).initTask()
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/AtcdThriftHandlerTask.py", line 227, in initTask
    self._links_lookup()
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/atcd/backends/linux.py", line 65, in _links_lookup
    raise Exception(msg)
Exception: One of the following interfaces does not exist: eth1, eth0
ERROR:AtcdVService:Unexpected Exception during init
Traceback (most recent call last):
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/sparts/vservice.py", line 268, in _runloop
    instance._createTasks()
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/sparts/vservice.py", line 167, in _createTasks
    self.tasks.init()
  File "/home/user/dev/atc/venv/lib/python2.7/site-packages/sparts/vtask.py", line 332, in init
    len(exceptions))
Exception: Unable to start service (2 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDeviceTimeoutTask.AtcdDeviceTimeoutTask object at 0x20ce310> to stop...
DEBUG:AtcdVService:Waiting for <atcd.backends.linux.AtcdLinuxShaper object at 0x20ce110> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDBQueueTask.AtcdDBQueueTask object at 0x20ce090> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdThriftHandlerTask.AtcdNBServerTask object at 0x1d89ed0> to stop...
INFO:AtcdVService:Instance shut down gracefully

Notice: i run this commands in virtualenv, and i activated it too.
maybe the problem is with the place of files in directories?
please, anyone have some idea why can't i run this?

**Comment by quelleck** [comment]
`CRITICAL:AtcdVService.AtcdLinuxShaper:One of the following interfaces does not exist: eth1, eth0`

Specify the name of your interfaces with `--atcd-lan name_of_interface` and `--atcd-wan name_of_interface` as arguments when you run `sudo actd`. Run `ifconfig -a` to get the names.

**Comment by dovodsc** [comment]
@quelleck I got the same error 'atcd' not found for command 'sudo atcd'. On ubuntu 18.04. While I'm do able to run 'atcd' without 'sudo'.

**Comment by dovodsc** [comment]
@dalmasi you may need to disable network interaces renaming for Ubuntu or set proper logical names for atcd as @quelleck   pointed out. 

@quelleck  I found solution for my issue 'sudo atcd' -> 'sudo ./atcd' weird. but works! )
