### ISSUE TITLE
sudo atcd produces an error

### ISSUE THREAD

**Issue by IoDmitri** [facebook/augmented-traffic-control#78]
Im running on a Mac OSX 10.10.  Error below. 
Traceback (most recent call last):
  File "/usr/local/bin/atcd", line 13, in <module>
    runner.run()
  File "/usr/local/lib/python2.7/site-packages/atcd/scripts/runner.py", line 34, in run
    initialize_thrift()
  File "/usr/local/lib/python2.7/site-packages/atcd/scripts/runner.py", line 27, in initialize_thrift
    AtcdThriftHandlerTask.factory().register()
  File "/usr/local/lib/python2.7/site-packages/atcd/AtcdThriftHandlerTask.py", line 203, in factory
    '{0} backend is not implemented!'.format(os_name.lower())
NotImplementedError: darwin backend is not implemented!

**Comment by chantra** [comment]
Hi @IoDmitri 

Unfortunately, ATC only supports Linux currently. We have obviously made a bad job at communicating this and are emphasizing this in some more obvious way.

Hopefully,  http://facebook.github.io/augmented-traffic-control/docs/install.html is clarifying the requirements.


Dup #68
